/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Accompaniments: () => import('#controllers/accompaniments_controller'),
  Dishes: () => import('#controllers/dishes_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Programs: () => import('#controllers/programs_controller'),
  PublicMenu: () => import('#controllers/public_menu_controller'),
  PublicOrders: () => import('#controllers/public_orders_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Users: () => import('#controllers/users_controller'),
}
