/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccompanimentSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'imagePublicId', 'imageUrl', 'isAvailable', 'name', 'priceCents', 'updatedAt'] as const
  $columns = AccompanimentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePublicId: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare isAvailable: boolean
  @column()
  declare name: string
  @column()
  declare priceCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DishSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'id', 'imagePublicId', 'imageUrl', 'isAvailable', 'name', 'priceCents', 'updatedAt'] as const
  $columns = DishSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePublicId: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare isAvailable: boolean
  @column()
  declare name: string
  @column()
  declare priceCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationLogSchema extends BaseModel {
  static $columns = ['body', 'channel', 'createdAt', 'error', 'id', 'kind', 'orderId', 'providerMessageId', 'recipient', 'status', 'updatedAt'] as const
  $columns = NotificationLogSchema.$columns
  @column()
  declare body: string | null
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare orderId: number | null
  @column()
  declare providerMessageId: string | null
  @column()
  declare recipient: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderEventSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'status'] as const
  $columns = OrderEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare status: string
}

export class OrderItemAccompanimentSchema extends BaseModel {
  static $columns = ['accompanimentId', 'createdAt', 'id', 'name', 'orderItemId', 'priceCents', 'updatedAt'] as const
  $columns = OrderItemAccompanimentSchema.$columns
  @column()
  declare accompanimentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare orderItemId: number
  @column()
  declare priceCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'dishId', 'id', 'name', 'orderId', 'priceCents', 'quantity', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dishId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare orderId: number
  @column()
  declare priceCents: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['address', 'code', 'createdAt', 'customerName', 'customerPhone', 'deliveryDate', 'deliveryFeeCents', 'deliveryTime', 'id', 'landmark', 'mode', 'note', 'paymentMethod', 'paymentStatus', 'status', 'totalCents', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerName: string | null
  @column()
  declare customerPhone: string | null
  @column.date()
  declare deliveryDate: DateTime
  @column()
  declare deliveryFeeCents: number
  @column()
  declare deliveryTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare landmark: string | null
  @column()
  declare mode: string
  @column()
  declare note: string | null
  @column()
  declare paymentMethod: string
  @column()
  declare paymentStatus: string
  @column()
  declare status: string
  @column()
  declare totalCents: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ProgramDishAccompanimentSchema extends BaseModel {
  static $columns = ['accompanimentId', 'createdAt', 'id', 'priceCents', 'programDishId', 'updatedAt'] as const
  $columns = ProgramDishAccompanimentSchema.$columns
  @column()
  declare accompanimentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priceCents: number
  @column()
  declare programDishId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProgramDishSchema extends BaseModel {
  static $columns = ['createdAt', 'dishId', 'id', 'priceCents', 'programId', 'scheduledDate', 'updatedAt'] as const
  $columns = ProgramDishSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dishId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priceCents: number
  @column()
  declare programId: number
  @column.date()
  declare scheduledDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProgramSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'endDate', 'id', 'startDate', 'title', 'updatedAt'] as const
  $columns = ProgramSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
