/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type DishTransformer from '#transformers/dish_transformer'
import type OrderDetailTransformer from '#transformers/order_detail_transformer'
import type OrderSummaryTransformer from '#transformers/order_summary_transformer'
import type ProgramDetailTransformer from '#transformers/program_detail_transformer'
import type ProgramSummaryTransformer from '#transformers/program_summary_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Dish = InferData<DishTransformer>
  export namespace Dish {
    export type Variants = InferVariants<DishTransformer>
  }
  export type OrderDetail = InferData<OrderDetailTransformer>
  export namespace OrderDetail {
    export type Variants = InferVariants<OrderDetailTransformer>
  }
  export type OrderSummary = InferData<OrderSummaryTransformer>
  export namespace OrderSummary {
    export type Variants = InferVariants<OrderSummaryTransformer>
  }
  export type ProgramDetail = InferData<ProgramDetailTransformer>
  export namespace ProgramDetail {
    export type Variants = InferVariants<ProgramDetailTransformer>
  }
  export type ProgramSummary = InferData<ProgramSummaryTransformer>
  export namespace ProgramSummary {
    export type Variants = InferVariants<ProgramSummaryTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
